name:                c14n
version:             0.1.0.1
github:              "mbg/c14n"
license:             MIT
author:              "Michael B. Gale"
maintainer:          "m.gale@warwick.ac.uk"
copyright:           "Copyright (c) Michael B. Gale"
category:            XML
synopsis:            Bindings to the c14n implementation in libxml.

description:         "Haskell bindings for the c14n implementation in libxml (XML canonicalisation).
                      See the README at <https://github.com/mbg/c14n#readme> for more information."

pkg-config-dependencies:
- libxml-2.0

extra-libraries:
- xml2

when:
- condition: os(darwin)
  extra-lib-dirs:
    - /usr/local/opt/libxml2/lib
  include-dirs:
    - /usr/local/opt/libxml2/include/libxml2

dependencies:
- base >= 4.8 && < 5
- bytestring >= 0.9 && < 0.11

library:
    source-dirs: src
    c-sources: cbits/*.c
    ghc-options:
    - -W